import Head from 'next/head';
import styles from '../styles/Home.module.css';
import React, { useEffect, useState } from 'react';
import Image from 'next/image';
import CardList from '../src/components/card-list/card-list.component';
import SearchBox from '../src/components/search-box/search-box.component';
export default function Home() {
  const [monsters, setMonsters] = useState(null);
  const [searchField, setSearchField] = useState(null);

  const [isLoading, setLoading] = useState(false);

  useEffect(() => {
    setLoading(true);
    fetch('https://jsonplaceholder.typicode.com/users')
      .then((res) => res.json())
      .then((data) => {
        setMonsters(data);
        setLoading(false);
      });
  }, []);

  if (isLoading) return <p>Looking for monsters...</p>;
  if (!monsters) return <p>No monsters around here</p>;
  const filteredMonsters = monsters.filter((monster) => {
    return monster.name.toLocaleLowerCase().includes(searchField);
  });

  var onSearchChange = (event) => {
    var searchField = event.target.value.toLocaleLowerCase();
    setSearchField(searchField);
  };

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>Welcome to Monsters Rolodex!</h1>
          <SearchBox
            placeholder={'Search for a monster'}
            onChangeHandler={onSearchChange}
          ></SearchBox>
          <CardList monsters={filteredMonsters}></CardList>

          {/* */}
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </>
  );
}
