import Head from 'next/head';
import styles from '../styles/Home.module.css';
import React, { useEffect, useState } from 'react';
import Image from 'next/image';
import SearchBox from '../src/components/search-box/search-box.component';
import MapaBazi from '../src/components/mapa-compoonent/mapa-bazi.component';
import BaziPage from './bazi';

export default function Home() {
  const [monsters, setMonsters] = useState([]);
  const [filteredMonsters, setFilteredMonsters] = useState(monsters);
  const [searchField, setSearchField] = useState('');
  const [searchFieldA, setSearchFieldA] = useState('');
  const [searchFieldB, setSearchFieldB] = useState('');
  const [isLoading, setLoading] = useState(false);

  console.log('render');
  useEffect(() => {
    // setLoading(true);
    // fetch('https://jsonplaceholder.typicode.com/users')
    //   .then((res) => res.json())
    //   .then((data) => {
    //     setMonsters(data);
    //     setLoading(false);
    //   });
  }, []);

  useEffect(() => {
    const newfilteredMonsters = monsters.filter((monster) => {
      return monster.name.toLocaleLowerCase().includes(searchField);
    });
    setFilteredMonsters(newfilteredMonsters);
  }, [monsters, searchField]);

  if (isLoading) return <p>Looking for bazis...</p>;
  if (!monsters) return <p>No bazis around here</p>;

  var onSearchChangeA = (event) => {
    var value = event.target.value.toLocaleLowerCase();
    setSearchFieldA(value);
  };

  var onSearchChangeB = (event) => {
    var value = event.target.value.toLocaleLowerCase();
    setSearchFieldB(value);
  };

  return (
    <>
      <div
        className={styles.monsterly}
        style={{
          backgroundColor: '#f5f5f7',
          fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
          color: '#111',
          minHeight: '100vh'
        }}
      >
        <Head>
          <title>Calculadora de Wu Xing (五行)</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
          <link
            href="https://fonts.googleapis.com/css2?family=Bigelow+Rules&family=EB+Garamond&display=swap"
            rel="stylesheet"
          />
        </Head>
        <main className={styles.main}>

          <div className={styles.threeCol}>
            <div>
              <SearchBox
                placeholder={'Search for a team (A)'}
                onChangeHandler={onSearchChangeA}
              ></SearchBox>
              <MapaBazi filter={searchFieldA}></MapaBazi>
            </div>
            <div>
              <BaziPage />
            </div>
            <div>
              <SearchBox
                placeholder={'Search for a team (B)'}
                onChangeHandler={onSearchChangeB}
              ></SearchBox>
              <MapaBazi filter={searchFieldB}></MapaBazi>
            </div>
          </div>
            <hr style={{ width: '90%', margin: '2rem auto' }} />
            {/* Embedded Bazi calculator */}
         

          <h1 className={styles.monstersTitle}>86</h1>
          {/* */}
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </>
  );
}
